### ISSUE TITLE
Generator is broken

### ISSUE THREAD

**Issue by btdrawer** [trayio/generator-trayio-nodejs-connector#33]
The yeoman generator seems to be completely broken at the moment:

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/generators/app/templates/.editorconfig
    at EditionInterface.exports.copy (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.copyFiles (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/generators/app/index.js:190:11)
    at Object.<anonymous> (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/yeoman-generator/lib/index.js:655:25)
    at /Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at /Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.once.once (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/yeoman-generator/lib/index.js:656:11)
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/benjamindrawer/.nvm/versions/node/v12.4.0/lib/node_modules/generator-trayio-nodejs-connector/node_modules/yeoman-generator/lib/index.js:676:20)
    at processImmediate (internal/timers.js:439:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by Ryanbarker0** [comment]
@btdrawer has this been fixed?
